### ISSUE TITLE
V0.12.0 Pre-launch checklist

### ISSUE THREAD

**Issue by hopskipnfall** [hopskipnfall/EmuLinker-K#114]
- [x] Performance testing
- [ ] Verify rooms are discarded when user leaves
- [ ] Verify users time out as expected
- [ ] Verify server shows up in Emulinker list
- [ ] Verify server shows up in Kaillera list
- [ ] Verify admin commands
- [ ] Verify normal commands
- [ ] Check for in game lag when another user:
  - [ ] Sends a chat message
  - [ ] Closes a game (this might be a problem)
  - [ ] Joins the server
  - [ ] Creates a new game
  - [ ] Starts a new game
- [ ] Feature testing
  - [ ] Shows up in Emulinker list
  - [ ] Shows up in Kaillera list
